<div id='slider'>
 <ul class='main-orbit' data-orbit data-options='resume_on_mouseout:true'>
   <?php echo $page->slides; ?>
 </ul>
</div>
<div data-magellan-expedition='fixed' class='second-nav'>
 <div class='row'>
   <div class='small-12 medium-7 medium-centered large-7 large-centered columns'>
     <dl class='sub-nav'>
       <dd data-magellan-arrival='freifunk-description'><a href='#freifunk-description'>Freifunk</a></dd>
       <dd data-magellan-arrival='freifunk-faq'><a href='#freifunk-faq'>Häufige Fragen</a></dd>
       <dd data-magellan-arrival='timeline'><a href='#timeline'>Timeline</a></dd>
       <dd data-magellan-arrival='mitmachen'><a href='#mitmachen'>Mitmachen</a></dd>
       <dd data-magellan-arrival='kontakt'><a href='#kontakt'>Kontakt</a></dd>
     </dl>
   </div>
 </div>
</div>

<section id='freifunk-description' data-magellan-destination='freifunk-description' class='info container row'>
 <div class='large-12 columns text-center'>
   <h2>Freifunk</h2>
   <h3 class='subheader'><small>WLAN von Bürgern für Bürger</small></h3>
   <p>
     Freifunk hat das Ziel ein freies, von Bürgern verwaltetes WLAN-Netz aufzubauen. Jeder Nutzer im Freifunk-Netz stellt seinen WLAN-Router für den Datentransfer der anderen Teilnehmer zur Verfügung. Es ist auch möglich den Internetzugang zur Verfügung zu stellen und somit anderen den Zugang zum weltweiten Netz zu ermöglichen. Durch ein sogenanntes Mesh-Netz verbinden sich der Freifunk-Router mit allen Freifunk-Routern in Reichweite und finden stets die bestmögliche Verbindung. So kann es zum Beispiel auch möglich sein ins Internet zu gelangen, wenn der eigene Anschluss mal gestört sein sollte.
   </p>
   <div class='row'>
     <div class='columns large-4'>
       <span class='fa-stack fa-4x'>
         <i class='fa fa-circle fa-stack-2x text-primary'></i>
         <i class='fa fa-wifi fa-stack-1x fa-inverse'></i>
       </span>
       <h4>Mesh</h4>
       <p>Ein Meshnetz zwischen den Routern sorgt für Stabilität und ermöglicht immer die schnellste Verbindung zum jeweiligen Dienst.</p>
     </div>
     <div class='columns large-4'>
       <span class='fa-stack fa-4x'>
         <i class='fa fa-circle fa-stack-2x text-primary'></i>
         <i class='fa fa-lock fa-stack-1x fa-inverse'></i>
       </span>
       <h4>Sicherheit</h4>
       <p>Das Freifunk-Netz ist vom heimischen Netz getrennt und kann nicht von dort erreicht werden. Mithilfe eines verschlüsselten Tunnels zwischen den Routern und dem Austrittsort ins Internet lässt sich die Verbindung nicht zurück verfolgen.</p>
     </div>
     <div class='columns large-4'>
       <span class='fa-stack fa-4x'>
         <i class='fa fa-circle fa-stack-2x text-primary'></i>
         <i class='fa fa-laptop fa-stack-1x fa-inverse'></i>
       </span>
       <h4>Mobilität</h4>
       <p>Je mehr sich an Freifunk beteiligen, desto Mobiler kann man sich im Freifunk-Netz bewegen. Nehme teil und erweitere das Netzwerk.</p>
     </div>
   </div><!-- #row -->
 </div><!-- #large-12 -->
</section><!-- #freifunk-description -->


<section id='freifunk-faq' data-magellan-destination='freifunk-faq' class='info container row background_gray'>
    <div class='large-12 columns text-center'>
      <h2>H&auml;ufige Fragen</h2>
      <h3 class='subheader'><small>in einfachen Worten erklärt!</small></h3>
      <p>
        Freifunk hat das Ziel ein freies, von Bürgern verwaltetes WLAN-Netz aufzubauen. Jeder Nutzer im Freifunk-Netz stellt seinen WLAN-Router für den Datentransfer der anderen Teilnehmer zur Verfügung. Es ist auch möglich den Internetzugang zur Verfügung zu stellen und somit anderen den Zugang zum weltweiten Netz zu ermöglichen. Durch ein sogenanntes Mesh-Netz verbinden sich der Freifunk-Router mit allen Freifunk-Routern in Reichweite und finden stets die bestmögliche Verbindung. So kann es zum Beispiel auch möglich sein ins Internet zu gelangen, wenn der eigene Anschluss mal gestört sein sollte.
      </p>
      <div class='row info-box'>
        <div class='columns large-4'>
          <img class='responsive' src='https://placehold.it/350x200'></img>
        </div>
        <div class='columns large-8 text-justify'>
          <h4>Freifunk-Router</h4>
          <p>Für Freifunk benötigt man einen Router mit einer speziellen Freifunk-Software. Nicht erschrecken, es klingt komplizierter als es ist. Router bekommt man schon ab 15€ und die Software lässt sich bei vielen Modellen so einfach wie ein Firmware Update aufspielen. Auf unseren regelmäßigen Treffen helfen wir gerne bei der Einrichtung und beraten welches Modell sich am besten Eignet.
          <br/>Eine gute Übersicht bieten wir auch in unserem Wiki.</p>
        </div>
      </div>

      <div class='row info-box'>
        <div class='columns large-8 text-justify'>
          <h4 class='text-upper'>Verbindung zum Internet</h4>
          <p>Wenn du deinen Freifunk-Router ans Internet anbindest, baut dieser eine verschlüsselte Verbindung zu einem Verteilknoten auf. Dieser Verteilknoten weiß wo sich die anderen Freifunk-Router befinden und stellt zusätzlich eine verschlüsselte Verbindung zu einem Austrittsort ins Internet.
            <br/>Der Austrittsort befindet sich im EU-Ausland oder bei einem Internetprovider, sodass die sonst übliche Störerhaftung nicht zutrifft. Da eine Webseite nur den Austrittsort sieht kann es vorkommen das Google auf Schwedisch oder Holländisch ist da es denkt das man sich dort befindet.</p>
        </div>
        <div class='columns large-4'>
          <img class='responsive' src='https://placehold.it/350x200'></img>
        </div>
      </div>

      <div class='row info-box'>
        <div class='columns large-4 '>
          <img class='responsive' src='https://placehold.it/350x200'></img>
        </div>
        <div class='columns large-8 text-justify'>
          <h4>Für wen ist Freifunk?</h4>
          <p>Mit Freifunk hast du die Möglichkeit deinen Internetanschluss ohne Risiko zur Verfügung zu stellen. Ob deinen Freunden oder den Freunden deiner Kinder, deinen Gäste im Lokal, Hotel oder Club, mit Freifunk kannst du deinen Anschluss unkompliziert und sicher teilen.
            <br/>Da Freifunk vom eigenen Heimnetz getrennt ist bleiben deine Daten im Heimischen netz unberührt.
            <br/>Doch Freifunk ist nicht nur Internet: Über das Freifunk-Netz lassen sich auch selbst Dienste anbieten, welche auch unabhängig von kommerziellen Anbietern oder auch bei Ausfällen des Internets in der Nachbarschaft erreichbar sind.</p>
        </div>
      </div>
    </div>
</section>

<?=renderTimeline($pages->find("template=post, timeline=1, sort=-date, limit=6"))?>

<section id='mitmachen' data-magellan-destination='mitmachen' class='info container row background_gray'>
  <div class='large-12 columns'>
    <div class='text-center'>
      <h2>Mitmachen</h2>
      <h3 class='subheader'><small>erweitere mit uns das Freifunk Netz</small></h3>
      <p>
        Gerne kannst du zu einem unserer regelmäßig (jeden 1. Dienstag 19:30) stattfindenden Treffen im Clostersudhaus in der Triererstraße 105 in 56072 Koblenz kommen. Wir beantworten alle Fragen und helfen beim Einrichten neuer Router.
        Natürlich hält dich niemand davon ab einfach weiter auf unserer Webseite und im Wiki zu stöbern. Bei Fragen kannst du auch unsere Mailinglist kontaktieren.
      </p>
    </div>
  </div>
  <div class='row'>
    <div class='medium-4 columns'>
      <h2>Starter-Kit</h2>
      <h3 class='subheader'><small>Wohnung, Geschäft, Café, Restaurant, Bar</small></h3>
      <dl>
        <dt>Du möchtest</dt>
        <dd>
          <ul>
            <li>dich mit dem Freifunk-Netz in deiner Nachbarschaft verbinden.</li>
            <li>deinen Internet-Anschluss freigeben.</li>
            <li>den ersten Freifunk-Router in deiner Umgebung aufstellen.</li>
          </ul>
        </dd>
        <dt>So kannst du mitmachen</dt>
        <dd>
          <ul>
            <li>
              Besorge einen Freifunk-fähigen Router. Empfehlungen:
              <span data-original-title='TP-Link TL-WDR4300, ~70 EUR, 2.4 GHz und 5 GHz.' class='description' data-toggle='tooltip' title=''>TL-WR-841N</span>,
              <span data-original-title='TP-Link TL-WR842ND, ~30 EUR, nur 2.4 GHz, etwas knappe 32MB RAM.' class='description' data-toggle='tooltip' title=''>TL-WDR4300</span>.
            </li>
            <li>
              Falls du deinen Internet-Zugang freigeben möchtest, musst du deinen VPN Key auf unserer Webseite <a href="<?=$pages->get('/node/')->httpUrl?>add">eintragen</a>.
              Danach kannst du den Router ans Internet anschließen.
              <!-- TODO: Link (wie komme ich an den account?) -->
            </li>
            <li>
              Gehe wie im <a href='../howto'>HowTo</a> beschrieben vor, um die Firmware zu flashen und zu konfigurieren.
            </li>
            <li>Stelle den Router an einem geeigneten Ort auf (z.B. Fensterbank).</li>
          </ul>
        </dd>
      </dl>
    </div>
    <div class='medium-4 columns'>
      <h2>Level 2</h2>
      <h3 class='subheader'><small>Balkon, hohes Gebäude, öffentlicher Platz, Park, weitläufiges Gelände</small></h3>
      <dl>
        <dt>Du möchtest</dt>
        <dd>
          <ul>
            <li>
              das Freifunk-Netz auf ein größeres Gebiet erweitern. Dazu eignen
              sich insbesondere höher gelegene Standorte (z.B. Balkone oder
              Dächer) auf 2.4 GHz.
            </li>
            <li>
              eine Verbindung zu einem weiter entfernten (bis ~5km)
              Freifunk-Router herstellen. Für stabile Verbindungen wird eine freie
              Sicht zum entfernten Router sowie das 5 GHz-Band benötigt.
            </li>
          </ul>
        </dd>
        <dt>So kannst du mitmachen</dt>
        <dd>
          <ul>
            <li>
              Besorge einen Freifunk-fähigen Outdoor-Router. Empfehlungen:
              <ul>
                <li>
                  <span data-original-title='Ubiquiti NanoStation M2, ~80 EUR, 2.4 GHz, 32MB RAM.' class='description' data-toggle='tooltip' title=''>NanoStation M2</span> oder
                  <span data-original-title='Ubiquiti NanoStation M2 loco, ~60 EUR, 2.4 GHz, 32MB RAM.' class='description' data-toggle='tooltip' title=''>M2 loco</span> oder
                  <span data-original-title='TP-Link CPE210, ~50 EUR, 2.4 GHz, 64MB RAM.' class='description' data-toggle='tooltip' title=''>TL-CPE 210</span> (alle 2.4 GHz)
                </li>
                <li>
                  <span data-original-title='Ubiquiti NanoStation M5, ~80 EUR, 5 GHz, 32MB RAM.' class='description' data-toggle='tooltip' title=''>NanoStation M5</span> oder
                  <span data-original-title='Ubiquiti NanoStation M5 loco, ~60 EUR, 5 GHz, 32MB RAM.' class='description' data-toggle='tooltip' title=''>M5 loco</span> (alle 5 GHz).
                </li>
              </ul>
            </li>
            <li>
              Eventuell kannst du diese Hardware im Rahmen einer
              <a href='https://wiki.freifunk.net/Berlin:%C3%9Cberlassungserkl%C3%A4rung' class='externalLink'>Überlassungserklärung</a> leihen.
            </li>
            <li>
              Zur Planung der neuen Verbindungen solltest du mit den Freifunker_innen,
              die die entfernten Router betreiben, <a href='../../contact'>Kontakt aufnehmen</a>.
            </li>
          </ul>
        </dd>
      </dl>
    </div>
    <div class='medium-4 columns'>
      <h2>Backbone</h2>
      <h3 class='subheader'><small>Dach, Dachgeschoss, hohes Gebäude, öffentliches Gebäude, Rathaus, Kirchturm...</small></h3>
      <dl>
        <dt>Du möchtest</dt>
        <dd>
          <ul>
            <li>
              das \"Rückgrat\" des Freifunk-Netzes stärken, indem du stabile
              Richtfunk-Verbindungen zu weit entfernten Freifunk-Routern
              aufbaust (bis ~10km). Für stabile Verbindungen wird eine freie
              Sicht zum entfernten Router benötigt.
            </li>
          </ul>
        </dd>
        <dt>So kannst du mitmachen</dt>
        <dd>
          <ul>
            <li>
              Besorge mehrere Freifunk-fähige Outdoor-Router für 5 GHz. Empfehlungen:
              <ul>
                <li> <span data-original-title='Ubiquiti NanoStation M5, ~80 EUR, 5 GHz.' class='description' data-toggle='tooltip' title=''>NanoStation M5</span> (bis ~5 km) </li>
                <li> <span data-original-title='Ubiquiti NanoBridge M5, ~80 EUR, 5 GHz.' class='description' data-toggle='tooltip' title=''>NanoBridge M5</span> (bis ~10 km) </li>
              </ul>
            </li>
            <li>Eventuell kannst du diese Hardware im Rahmen einer <a href='https://wiki.freifunk.net/Berlin:%C3%9Cberlassungserkl%C3%A4rung' class='externalLink'>Überlassungserklärung</a> leihen. </li>
            <li>Zur Planung der neuen Verbindungen solltest du mit den Freifunker_innen, die die entfernten Router betreiben, <a href='../../contact'>Kontakt aufnehmen</a>.</li>
          </ul>
        </dd>
      </dl>
    </div>
  </div>
</section>

<section id='kontakt' data-magellan-destination='kontakt' class='info container row'>
 <div class='large-12 columns text-center'>
   <h2>Kontakt</h2>
   <h3 class='subheader'><small>Nutzen Sie unser Kontaktformular oder tragen SIe sich in unsere Mailinglist ein.</small></h3>

   <form name="contactform" method="post" action="<?=$config->urls->templates?>scripts/contact_me.php" id="contactForm">
       <div class="row">
           <div class="medium-6 columns">
               <div class="form-group">
                   <input type="text" class="form-control" placeholder="Dein Name *" id="name" required data-validation-required-message="Bitte Name eintragen.">
                   <p class="help-block text-danger"></p>
               </div>
               <div class="form-group">
                   <input type="email" class="form-control" placeholder="E-Mail Adresse *" id="email" required data-validation-required-message="Bitte E-Mail Adresse eintragen.">
                   <p class="help-block text-danger"></p>
               </div>
               <div class="form-group">
                   <input type="tel" class="form-control" placeholder="Telefonnummer " id="phone" >
                   <p class="help-block text-danger"></p>
               </div>
           </div>
           <div class="medium-6 columns">
               <div class="form-group">
                   <textarea class="form-control" placeholder="Deine Nachricht *" id="message" required data-validation-required-message="Please enter a message."></textarea>
                   <p class="help-block text-danger"></p>
               </div>
           </div>
           <div class="large-12 columns text-center">
             <div class="form-group datenschutz">
               <input type="checkbox" required data-validation-required-message="Ohne einverständnis können wir die Anfrage nicht verarbeiten!"> ich bin mit dem <a data-toggle="modal" data-target="#myModal">Datenschutz</a> einverstanden.
             </div>
           </div>
           <div class="clearfix"></div>
           <div class="large-12 columns text-center">
               <div id="success"></div>
               <button type="submit" class="btn btn-xl">Absenden</button>
           </div>
       </div>
 </div><!-- #large-12 -->
</section><!-- #freifunk-description -->
