<article id='article' class='medium-9 small-12 columns'>
  <h1>Password zurücksetzen</h1>

  <form action='./pwreset' id="form_2" method="get">
    <label for="email">E-Mail</label>
    <input type="text" id="email" name="email" maxlength="40">
    <button class='button' type='submit' name='submit' value='add'>Password Zurücksetzen</button>
  </form>

</article>
<aside id="sidebar" class="medium-3 small-12 columns">
  <?=$page->userlist?>
</aside>
