<li <?=$leftright?>>
  <div class='timeline-image'>
    <img class='img-circle img-responsive' src='<?=$image?>' alt='<?=$image_description?>'>
  </div>
  <div class='timeline-panel'>
    <div class='timeline-heading'>
      <h4> <?=$title?> </h4>
      <h4 class='subheading'> <?=$subtitle?></h4>
    </div>
    <div class='timeline-body'>
      <p class='text-muted'>
        <?=$summary?> <a href='<?=$readmore?>'>Weiterlesen</a>
      </p>
    </div>
  </div>
</li>
