<section id='timeline' data-magellan-destination='timeline' class='info container'>
  <div class='row'>
    <div class='columns large-12 text-center'>
      <h2 class='section-heading'>Timeline</h2>
      <h3 class='subheader'><small>Unser Weg zum freien Netz.</small></h3>
    </div>
  </div>
  <div class='row'>
    <div class='large-12 columns'>
      <ul class='timeline'>
        <?=$timeline_blocks?>
        <li class='timeline-inverted'>
          <div class='timeline-image'>
            <h4>Werde
              <br>Teil unserer
              <br>Community!</h4>
            </div>
          </li>
        </ul><!-- #timelines -->
      </div>
    </div>
  </div>
</section><!-- #timeline -->
