<?php

class InputfieldNodeInfo extends Inputfield {

	public static function getModuleInfo() {
		return array(
			'title' => 'Node Info Inputfield',
			'version' => 001,
			'summary' => 'Input field for the node information.',
			'requires' => 'FieldtypeNodeInfo',
			);
	}

	protected $page;
	protected $field;

	public function setPage(Page $page) {
		$this->page = $page;
	}

	public function setField(Field $field) {
		$this->field = $field;
	}

	/**
	 * Render the entire input area for NodeInfo
	 */
  public function ___render() {

		$name = $this->attr('name');

		$out = "
			<div class='nodeinfo'>
				<h2>Node Information</h2>
				<h4>Last Connection</h4>

				<h4>IPv6</h4>

				<h4>Hardware</h4>

				<h4>Firmware</h4>

				<h4>Latitude / Longitude</h4>

				<h4>Address</h4>

				<h4>Online Status</h4>
				
			</div>";
  }

	/**
	 * Processe input for the NodeInfo inputs (actually no input)
	 */
	public function ___processInput(WireInputData $input) {

	}

}
